{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "elk.elasticsearchFullname" . }}-headless
  labels:
    {{- include "elk.labels" . | nindent 4 }}
    app.kubernetes.io/component: elasticsearch
spec:
  clusterIP: None
  selector:
    {{- include "elk.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: elasticsearch
  ports:
    - name: http
      port: {{ .Values.elasticsearch.service.port }}
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "elk.elasticsearchFullname" . }}
  labels:
    {{- include "elk.labels" . | nindent 4 }}
    app.kubernetes.io/component: elasticsearch
spec:
  type: ClusterIP
  selector:
    {{- include "elk.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: elasticsearch
  ports:
    - name: http
      port: {{ .Values.elasticsearch.service.port }}
      targetPort: http
{{- end }}
