spring:
  application:
    name: cash-service
  config:
    import:
      - classpath:application-local.yml
      - classpath:resilience4j-accounts.yml
      - optional:configserver:http://${CONFIG_SERVER_HOST:localhost}:8888
