spring:
  cloud:
    gateway:
      routes:
        - id: accounts-service
          uri: lb://ACCOUNTS-SERVICE
          predicates:
            - Path=/api/accounts/**
        - id: cash-service
          uri: lb://CASH-SERVICE
          predicates:
            - Path=/api/cash/**
        - id: transfer-service
          uri: lb://TRANSFER-SERVICE
          predicates:
            - Path=/api/transfers/**
        - id: notifications-service
          uri: lb://NOTIFICATIONS-SERVICE
          predicates:
            - Path=/api/notifications/**

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health,info

---
spring:
  config:
    activate:
      on-profile: secure
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8090/realms/mybank}
app:
  security:
    enabled: true
