spring:
  cloud:
    gateway:
      routes:
        - id: accounts-service
          uri: http://accounts-service:8091
          predicates:
            - Path=/api/accounts/**
        - id: cash-service
          uri: http://cash-service:8092
          predicates:
            - Path=/api/cash/**
        - id: transfer-service
          uri: http://transfer-service:8093
          predicates:
            - Path=/api/transfers/**

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info

---
spring:
  config:
    activate:
      on-profile: secure
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8090/realms/mybank}
app:
  security:
    enabled: true
