spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:mybank}
    username: ${POSTGRES_USER:mybank}
    password: ${POSTGRES_PASSWORD:mybank}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate.default_schema: transfer
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: transfer
    liquibase-schema: public

server:
  port: 8093

app:
  kafka:
    topic: ${APP_KAFKA_TOPIC:bank.notifications}
  accounts:
    base-url: ${APP_ACCOUNTS_BASE_URL:http://localhost:8081}
  transfer:
    sender-username: demo.user

management:
  endpoints:
    web:
      exposure:
        include: health,info

---
spring:
  config:
    activate:
      on-profile: secure
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8090/realms/mybank}
      client:
        registration:
          services-client:
            provider: keycloak
            client-id: mybank-services
            client-secret: ${KEYCLOAK_SERVICE_SECRET:services-secret-change-me}
            authorization-grant-type: client_credentials
            scope: openid
        provider:
          keycloak:
            token-uri: ${KEYCLOAK_TOKEN_URI:http://localhost:8090/realms/mybank/protocol/openid-connect/token}
            jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://localhost:8090/realms/mybank/protocol/openid-connect/certs}
app:
  security:
    enabled: true
  oauth2:
    client-registration-id: services-client
