apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-oauth
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
stringData:
  KEYCLOAK_SERVICE_SECRET: {{ .Values.global.keycloak.serviceSecret | quote }}
  KEYCLOAK_FRONT_SECRET: {{ .Values.global.keycloak.frontSecret | quote }}
