spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:mybank}
    username: ${POSTGRES_USER:mybank}
    password: ${POSTGRES_PASSWORD:mybank}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate.default_schema: cash
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: cash
    liquibase-schema: public

server:
  port: 8092

app:
  accounts:
    base-url: ${APP_ACCOUNTS_BASE_URL:http://localhost:8081}
  notifications:
    base-url: ${APP_NOTIFICATIONS_BASE_URL:http://localhost:8081}
  cash:
    fallback-username: demo.user

resilience4j:
  circuitbreaker:
    instances:
      accounts:
        sliding-window-size: 10
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        wait-duration-in-open-state: 10s
        failure-rate-threshold: 50
  retry:
    instances:
      accounts:
        max-attempts: 3
        wait-duration: 200ms
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
        ignore-exceptions:
          - com.mybank.cash.service.CashOperationException
          - org.springframework.web.client.RestClientResponseException

---
spring:
  config:
    activate:
      on-profile: secure
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8090/realms/mybank}
      client:
        registration:
          services-client:
            provider: keycloak
            client-id: mybank-services
            client-secret: ${KEYCLOAK_SERVICE_SECRET:services-secret-change-me}
            authorization-grant-type: client_credentials
            scope: openid
        provider:
          keycloak:
            token-uri: ${KEYCLOAK_TOKEN_URI:http://localhost:8090/realms/mybank/protocol/openid-connect/token}
            jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://localhost:8090/realms/mybank/protocol/openid-connect/certs}
app:
  security:
    enabled: true
  oauth2:
    client-registration-id: services-client
